// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
          return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28W647o4zrAZisrQNLfrn_4CXN_jjeIg',
    appId: '1:242560270718:web:87611aa3c9fe32e5ccb32f',
    messagingSenderId: '242560270718',
    projectId: 'tooltrack-ee0aa',
    authDomain: 'tooltrack-ee0aa.firebaseapp.com',
    storageBucket: 'tooltrack-ee0aa.firebasestorage.app',
    measurementId: 'G-C24WJBSVCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRzqWv3SraB_jZjom-G8FLEjB6LvSnig',
    appId: '1:242560270718:android:35204c637ffe1863ccb32f',
    messagingSenderId: '242560270718',
    projectId: 'tooltrack-ee0aa',
    storageBucket: 'tooltrack-ee0aa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28W647o4zrAZisrQNLfrn_4CXN_jjeIg',
    appId: '1:242560270718:web:f9999e456c6181e6ccb32f',
    messagingSenderId: '242560270718',
    projectId: 'tooltrack-ee0aa',
    authDomain: 'tooltrack-ee0aa.firebaseapp.com',
    storageBucket: 'tooltrack-ee0aa.firebasestorage.app',
    measurementId: 'G-CWFRQ5FFZB',
  );

    static const FirebaseOptions ios = FirebaseOptions(
                apiKey: 'AIzaSyCBdT1E83YRvplBukX9t1bdDTymViz3-6k',
                appId: '1:242560270718:ios:52f3c941785f469bccb32f',
                messagingSenderId: '242560270718',
                projectId: 'tooltrack-ee0aa',
                storageBucket: 'tooltrack-ee0aa.firebasestorage.app',
                iosClientId: '242560270718-nrq1kk5mg60i7so7li93s7ip8vfa9t6n.apps.googleusercontent.com',
                iosBundleId: 'com.toolkeeper.app',
            );
}
